### ISSUE TITLE
No listing under View Transform

### ISSUE THREAD

**Issue by meetdilip** [khlorghaal/blender-ACES-simple-simplified#1]
I have added the folder and replaced the **config.ocio** with the one in this repo as suggested in the ReadMe. But there is no listing on View Transform drop down. Thanks.

This is on Ubuntu 22.04 and 3.22

**Comment by meetdilip** [comment]
Works fine on Windows 10 and Blender 3.0.

**Comment by khlorghaal** [comment]
Works On My Machine

**Comment by meetdilip** [comment]
I do not know why. I can see the entry under " Sequencer " though. Nothing under " View Transform ".

I am using v3.3now. Thanks.
