### ISSUE TITLE
For windows users they can use Appdata folder

### ISSUE THREAD

**Issue by sacb0y** [khlorghaal/blender-ACES-simple-simplified#2]
`C:\Users\[user]\AppData\Roaming\Blender Foundation\Blender\3.3\datafiles\colormanagement` is a valid directory for this.

I reccomend adding this to the readme.

**Comment by sacb0y** [comment]
As long as they copy the original colormanagement folder over otherwise they'll get crashes

**Comment by khlorghaal** [comment]
👍
