### ISSUE TITLE
Crash when adjusting "look"

### ISSUE THREAD

**Issue by sacb0y** [khlorghaal/blender-ACES-simple-simplified#3]
There's a crash when adjusting the look setting below view transform after setting ACES. 

Occurs only in rendered mode.

**Comment by sacb0y** [comment]
For likely the same reason will crash

**Comment by sacb0y** [comment]
Sorry new to github stuff*

Anyway will also crash when opening a old project if the project has render mode enabled.

**Comment by sacb0y** [comment]
NVM I'm dumb, I needed to copy the original color management folder over.

**Comment by khlorghaal** [comment]
odd, when i updated and opened a project, it auto reverted to standard
